cargo-features = ["edition"]

[package]
name = "zycord_serenity"
version = "0.1.0"
authors = ["th0rex"]
edition = "2018"

[dependencies]
arrayvec = "0.4.7"
serenity = "0.5.9"
shared = { path = "../shared" }
